const input = [
    {
        "id": "8ede1ae8-e3bf-4506-ab98-fb666bcd7037",
        "label": "no_kk",
        "xmin": 351,
        "ymin": 53,
        "xmax": 632,
        "ymax": 99,
        "score": 0.91211134,
        "ocr_text": "3309091212190004",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "d8f5bc84-f17e-4ade-9304-3c8370324f4a",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "dd158d88-debb-4bdb-927a-6477551a8bef",
        "label": "nama_kk",
        "xmin": 234,
        "ymin": 108,
        "xmax": 298,
        "ymax": 125,
        "score": 0.51274306,
        "ocr_text": "TRISUTRISNO",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "8b92ea20-b580-4c3b-b290-7b1ab54cdf47",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "ee7eea86-e97c-4f84-b741-e27f60fa913a",
        "label": "kode_pos",
        "xmin": 234,
        "ymin": 145,
        "xmax": 263,
        "ymax": 156,
        "score": 0.64787745,
        "ocr_text": "57373",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "9b1f7cab-3e6f-4108-9ef5-4976c23374e4",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "2e6bb8d4-f30b-4503-9a4a-98d5e53dfa19",
        "label": "desa_kelurahan",
        "xmin": 721,
        "ymin": 70,
        "xmax": 770,
        "ymax": 84,
        "score": 0.9164068,
        "ocr_text": "KETAON",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "37d4e445-e21c-4ace-bc18-c68347fc942d",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "ec025dd8-b552-4967-b486-952c8dba4e6b",
        "label": "kabupaten",
        "xmin": 722,
        "ymin": 93,
        "xmax": 780,
        "ymax": 108,
        "score": 0.8848248,
        "ocr_text": "BOYOLALI",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "886802df-d6dd-467a-9ecd-3342505e766d",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "d2264ebd-6b3a-4db6-8fe8-c19e1f497ee2",
        "label": "kecamatan",
        "xmin": 722,
        "ymin": 81,
        "xmax": 797,
        "ymax": 96,
        "score": 0.9925135,
        "ocr_text": "BANYUDONO",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "55b7c0c9-d072-4b3c-ba22-1e18f5a99f18",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "698f3271-d8f8-45e1-a7cd-dfd73dc9f4b4",
        "label": "table",
        "xmin": 44,
        "ymin": 377,
        "xmax": 862,
        "ymax": 449,
        "score": 1,
        "ocr_text": "table",
        "type": "table",
        "cells": [
            {
                "id": "9aac28e9-952c-424e-abd0-0a26ca1d8a14",
                "row": 1,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "status_perkawinan",
                "xmin": 58,
                "ymin": 390,
                "xmax": 117,
                "ymax": 400,
                "score": 0.9995876,
                "text": "Janda",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "efceb7a4-c46b-4718-8fd5-70cb15b6d9fc",
                "lookup_edited": false
            },
            {
                "id": "a622b43e-8126-4f90-b62f-22965f3eabe6",
                "row": 1,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "status_hubungan",
                "xmin": 219,
                "ymin": 387,
                "xmax": 292,
                "ymax": 397,
                "score": 0.99487954,
                "text": "KEPALA KELUARGA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "2e0dcdbe-2550-4734-8451-0dd006ded8fa",
                "lookup_edited": false
            },
            {
                "id": "25a9c13f-835a-48fc-9bce-6a46907432f4",
                "row": 1,
                "col": 4,
                "row_span": 1,
                "col_span": 1,
                "label": "kewarganegaraan",
                "xmin": 314,
                "ymin": 386,
                "xmax": 331,
                "ymax": 395,
                "score": 0.9998716,
                "text": "WNI",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "a9e442b8-e099-4265-b0de-164cd6233434",
                "lookup_edited": false
            },
            {
                "id": "a5f5465a-7f49-4fa0-9577-c8d8d377cd7c",
                "row": 1,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ayah",
                "xmin": 547,
                "ymin": 382,
                "xmax": 575,
                "ymax": 390,
                "score": 0.99961215,
                "text": "KAYAT",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "abd4363b-606a-4b52-a0e2-431ebc966cae",
                "lookup_edited": false
            },
            {
                "id": "f82d7095-56bd-4965-9890-050b928223c8",
                "row": 1,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ibu",
                "xmin": 776,
                "ymin": 377,
                "xmax": 814,
                "ymax": 387,
                "score": 0.99898905,
                "text": "SUKHRI",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "90db6e16-4ce0-4004-a8e9-800071e55988",
                "lookup_edited": false
            },
            {
                "id": "198dbec1-bcde-4da4-ae6e-89f9044a5bff",
                "row": 2,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "status_perkawinan",
                "xmin": 59,
                "ymin": 405,
                "xmax": 117,
                "ymax": 413,
                "score": 0.9958036,
                "text": "KAWIN",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "efceb7a4-c46b-4718-8fd5-70cb15b6d9fc",
                "lookup_edited": false
            },
            {
                "id": "18b49e36-a247-4d9c-9c84-e5ce11684ae7",
                "row": 2,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "status_hubungan",
                "xmin": 223,
                "ymin": 403,
                "xmax": 241,
                "ymax": 410,
                "score": 0.9643195,
                "text": "ANAK",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "2e0dcdbe-2550-4734-8451-0dd006ded8fa",
                "lookup_edited": false
            },
            {
                "id": "37753080-dae6-42ba-89e7-9f5571420c41",
                "row": 2,
                "col": 4,
                "row_span": 1,
                "col_span": 1,
                "label": "kewarganegaraan",
                "xmin": 315,
                "ymin": 400,
                "xmax": 330,
                "ymax": 408,
                "score": 0.9617234,
                "text": "WNI",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "a9e442b8-e099-4265-b0de-164cd6233434",
                "lookup_edited": false
            },
            {
                "id": "12e20566-5868-4b23-8892-62da4540c5b9",
                "row": 2,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ayah",
                "xmin": 548,
                "ymin": 393,
                "xmax": 610,
                "ymax": 406,
                "score": 0.99149585,
                "text": "MUNDISUPOYO",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "abd4363b-606a-4b52-a0e2-431ebc966cae",
                "lookup_edited": false
            },
            {
                "id": "41f841c7-0fe9-4e72-8ffd-155b581d357a",
                "row": 2,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ibu",
                "xmin": 777,
                "ymin": 391,
                "xmax": 823,
                "ymax": 401,
                "score": 0.98697346,
                "text": "SRIGADES",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "90db6e16-4ce0-4004-a8e9-800071e55988",
                "lookup_edited": false
            },
            {
                "id": "ef8725e2-e177-4283-84b7-69e980f1b661",
                "row": 3,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "status_perkawinan",
                "xmin": 44,
                "ymin": 428,
                "xmax": 97,
                "ymax": 437,
                "score": 0.92072487,
                "text": "BELUM KAWIN",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "efceb7a4-c46b-4718-8fd5-70cb15b6d9fc",
                "lookup_edited": false
            },
            {
                "id": "80931792-62ad-43c1-a455-eb439c9e13a0",
                "row": 3,
                "col": 2,
                "row_span": 1,
                "col_span": 1,
                "label": "no_table_2",
                "xmin": 44,
                "ymin": 428,
                "xmax": 97,
                "ymax": 437,
                "score": 0.6174348,
                "text": "4",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "5e57cefa-7766-4ac9-bb1b-426e82cc88ea",
                "lookup_edited": false
            },
            {
                "id": "12249443-bfc4-4f1f-9073-82252b027c9e",
                "row": 3,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "status_hubungan",
                "xmin": 222,
                "ymin": 417,
                "xmax": 240,
                "ymax": 423,
                "score": 0.52747214,
                "text": "ANAK",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "2e0dcdbe-2550-4734-8451-0dd006ded8fa",
                "lookup_edited": false
            },
            {
                "id": "de0012d0-4d1f-40e5-b755-2b92ce1f127b",
                "row": 3,
                "col": 4,
                "row_span": 1,
                "col_span": 1,
                "label": "kewarganegaraan",
                "xmin": 315,
                "ymin": 416,
                "xmax": 329,
                "ymax": 422,
                "score": 0.43005037,
                "text": "WNI",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "a9e442b8-e099-4265-b0de-164cd6233434",
                "lookup_edited": false
            },
            {
                "id": "4cd736e9-055a-4c03-8f78-ab93ec1361e6",
                "row": 3,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ayah",
                "xmin": 548,
                "ymin": 408,
                "xmax": 605,
                "ymax": 420,
                "score": 0.58234483,
                "text": "THE SUTRISNO",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "abd4363b-606a-4b52-a0e2-431ebc966cae",
                "lookup_edited": false
            },
            {
                "id": "cee0f331-e202-4023-af30-000b2bab0cdd",
                "row": 3,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ibu",
                "xmin": 776,
                "ymin": 404,
                "xmax": 862,
                "ymax": 419,
                "score": 0.7757394,
                "text": "NUGRAHANINGSIN",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "90db6e16-4ce0-4004-a8e9-800071e55988",
                "lookup_edited": false
            },
            {
                "id": "d1a4a4db-4970-4bcf-aebf-50b132f1428c",
                "row": 4,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "status_hubungan",
                "xmin": 221,
                "ymin": 442,
                "xmax": 241,
                "ymax": 449,
                "score": 0.468169,
                "text": "ANAK",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "2e0dcdbe-2550-4734-8451-0dd006ded8fa",
                "lookup_edited": false
            },
            {
                "id": "53e3ab20-e7ad-4361-8b15-a97f411a343d",
                "row": 4,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ayah",
                "xmin": 550,
                "ymin": 439,
                "xmax": 604,
                "ymax": 448,
                "score": 0.79265755,
                "text": "TRIBUIDUINO",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "abd4363b-606a-4b52-a0e2-431ebc966cae",
                "lookup_edited": false
            },
            {
                "id": "6a6ed56a-e455-4bd0-aa2f-a127f8b233e1",
                "row": 4,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "ortu_ibu",
                "xmin": 778,
                "ymin": 436,
                "xmax": 862,
                "ymax": 448,
                "score": 0.6234147,
                "text": "NUGRAHANINDEH",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "90db6e16-4ce0-4004-a8e9-800071e55988",
                "lookup_edited": false
            }
        ],
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "badac68b-7628-4655-8f45-ed61031e6725",
        "label": "table",
        "xmin": 43,
        "ymin": 167,
        "xmax": 974,
        "ymax": 277,
        "score": 1,
        "ocr_text": "table",
        "type": "table",
        "cells": [
            {
                "id": "b7f082a6-02d5-4dbc-98c4-225fa9e9552a",
                "row": 1,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "nama_lengkap",
                "xmin": 126,
                "ymin": 201,
                "xmax": 134,
                "ymax": 209,
                "score": 0.99935,
                "text": "2",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "10280c92-ae97-4162-93b3-cf4cd39ea92a",
                "lookup_edited": false
            },
            {
                "id": "3b1621f9-bb88-4a9d-9c8a-a31c8f74fdc5",
                "row": 1,
                "col": 2,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_kelamin",
                "xmin": 332,
                "ymin": 197,
                "xmax": 364,
                "ymax": 209,
                "score": 0.9997309,
                "text": "L",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "b8449ba4-8f57-4182-b974-5f51f027dbc9",
                "lookup_edited": false
            },
            {
                "id": "697aa6fb-3adf-4ed2-90b2-6b7ee1be8385",
                "row": 1,
                "col": 4,
                "row_span": 1,
                "col_span": 1,
                "label": "tempat_lahir",
                "xmin": 522,
                "ymin": 189,
                "xmax": 539,
                "ymax": 198,
                "score": 0.9994803,
                "text": "LAM",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "94b31b78-ae3c-4a5f-9e1d-c0dda7c130dd",
                "lookup_edited": false
            },
            {
                "id": "08bac2f6-d64a-48d7-91a3-dff9d510955b",
                "row": 1,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "tempat_lahir",
                "xmin": 615,
                "ymin": 180,
                "xmax": 672,
                "ymax": 191,
                "score": 0.9986532,
                "text": "TASEDERAJAT",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "94b31b78-ae3c-4a5f-9e1d-c0dda7c130dd",
                "lookup_edited": false
            },
            {
                "id": "12de44a2-6853-49fa-9f1d-4d34f1907831",
                "row": 1,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "tanggal_lahir",
                "xmin": 482,
                "ymin": 191,
                "xmax": 509,
                "ymax": 200,
                "score": 0.99662787,
                "text": "081675",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "8b3da9b8-668a-4959-9b51-5e8ce3b05b95",
                "lookup_edited": false
            },
            {
                "id": "3400d483-d6e2-4222-8dbc-f23b6db2064a",
                "row": 1,
                "col": 7,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_pekerjaan",
                "xmin": 760,
                "ymin": 167,
                "xmax": 842,
                "ymax": 181,
                "score": 0.99998605,
                "text": "KARYAWAN SWASTA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "4f999028-320c-4f97-8074-52f021ed256c",
                "lookup_edited": false
            },
            {
                "id": "f17c80aa-bede-44f0-9f4e-99b8f06439a0",
                "row": 1,
                "col": 8,
                "row_span": 1,
                "col_span": 1,
                "label": "golongan darah",
                "xmin": 925,
                "ymin": 174,
                "xmax": 973,
                "ymax": 187,
                "score": 0.99997246,
                "text": "TIDAK TAHU",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "3d69e954-3d41-4b01-a08b-f557eea10c00",
                "lookup_edited": false
            },
            {
                "id": "d1dd3428-5199-45bc-983f-6ed90288b0c6",
                "row": 2,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "nama_lengkap",
                "xmin": 46,
                "ymin": 225,
                "xmax": 125,
                "ymax": 239,
                "score": 0.9902333,
                "text": "2MORAHANDON",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "10280c92-ae97-4162-93b3-cf4cd39ea92a",
                "lookup_edited": false
            },
            {
                "id": "f881fe56-cae7-4070-bee8-b90b3c03945b",
                "row": 2,
                "col": 2,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_kelamin",
                "xmin": 340,
                "ymin": 211,
                "xmax": 365,
                "ymax": 220,
                "score": 0.31942788,
                "text": "L",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "b8449ba4-8f57-4182-b974-5f51f027dbc9",
                "lookup_edited": false
            },
            {
                "id": "b67a7350-1bf1-42f3-9a54-3c64323a69bb",
                "row": 2,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "NIK",
                "xmin": 214,
                "ymin": 216,
                "xmax": 280,
                "ymax": 229,
                "score": 0.6866829,
                "text": "300004211830002",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "7dfc5ee4-4234-4f8c-a59f-232a89a50019",
                "lookup_edited": false
            },
            {
                "id": "ba01f376-9245-4b83-b3ab-d28ba971723c",
                "row": 2,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "tempat_lahir",
                "xmin": 605,
                "ymin": 207,
                "xmax": 671,
                "ymax": 221,
                "score": 0.5286578,
                "text": "BLTASEDERAJAT",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "94b31b78-ae3c-4a5f-9e1d-c0dda7c130dd",
                "lookup_edited": false
            },
            {
                "id": "f2541dd7-382e-45a8-941d-b070f85a1cf2",
                "row": 2,
                "col": 7,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_pekerjaan",
                "xmin": 760,
                "ymin": 195,
                "xmax": 855,
                "ymax": 210,
                "score": 0.80857843,
                "text": "BELUM/TIDAK BEKERJA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "4f999028-320c-4f97-8074-52f021ed256c",
                "lookup_edited": false
            },
            {
                "id": "5ac17c72-bcf4-40bd-b1ec-f8e85d0ce922",
                "row": 2,
                "col": 8,
                "row_span": 1,
                "col_span": 1,
                "label": "golongan darah",
                "xmin": 925,
                "ymin": 191,
                "xmax": 974,
                "ymax": 202,
                "score": 0.46244055,
                "text": "TIDAK TAHU",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "3d69e954-3d41-4b01-a08b-f557eea10c00",
                "lookup_edited": false
            },
            {
                "id": "637ea186-c7d5-466c-b96b-02ceaeaa6ebc",
                "row": 3,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "nama_lengkap",
                "xmin": 43,
                "ymin": 238,
                "xmax": 138,
                "ymax": 253,
                "score": 0.952961,
                "text": "3KA SUNYA SAMUDRA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "10280c92-ae97-4162-93b3-cf4cd39ea92a",
                "lookup_edited": false
            },
            {
                "id": "e4dc4fdf-7576-47a0-a2dd-82a2dd74a1a3",
                "row": 3,
                "col": 2,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_kelamin",
                "xmin": 332,
                "ymin": 224,
                "xmax": 366,
                "ymax": 235,
                "score": 0.48370782,
                "text": "Laki-Laki",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "b8449ba4-8f57-4182-b974-5f51f027dbc9",
                "lookup_edited": false
            },
            {
                "id": "f14678dd-b14e-45d5-9d4c-f2c5cf80b4b3",
                "row": 3,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "NIK",
                "xmin": 218,
                "ymin": 230,
                "xmax": 276,
                "ymax": 241,
                "score": 0.7698582,
                "text": "000170105000",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "7dfc5ee4-4234-4f8c-a59f-232a89a50019",
                "lookup_edited": false
            },
            {
                "id": "63109293-40d8-4add-9193-a685f9aa8aff",
                "row": 3,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "tempat_lahir",
                "xmin": 605,
                "ymin": 207,
                "xmax": 671,
                "ymax": 221,
                "score": 0.68831027,
                "text": "BLTASEDERAJAT",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "94b31b78-ae3c-4a5f-9e1d-c0dda7c130dd",
                "lookup_edited": false
            },
            {
                "id": "3169496f-ea5f-440f-b256-21854beee4ee",
                "row": 3,
                "col": 7,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_pekerjaan",
                "xmin": 762,
                "ymin": 212,
                "xmax": 847,
                "ymax": 225,
                "score": 0.79195154,
                "text": "PELAJAR/MAHASISWA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "4f999028-320c-4f97-8074-52f021ed256c",
                "lookup_edited": false
            },
            {
                "id": "86d3c96b-39b5-40fd-b6c0-de85977c30e2",
                "row": 3,
                "col": 8,
                "row_span": 1,
                "col_span": 1,
                "label": "golongan darah",
                "xmin": 926,
                "ymin": 206,
                "xmax": 974,
                "ymax": 216,
                "score": 0.6741543,
                "text": "TIDAK TAHU",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "3d69e954-3d41-4b01-a08b-f557eea10c00",
                "lookup_edited": false
            },
            {
                "id": "137185ea-d5c3-4bf2-94d4-c09702ce648d",
                "row": 4,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "nama_lengkap",
                "xmin": 57,
                "ymin": 250,
                "xmax": 129,
                "ymax": 264,
                "score": 0.9568976,
                "text": "NINORUM LARASAT",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "10280c92-ae97-4162-93b3-cf4cd39ea92a",
                "lookup_edited": false
            },
            {
                "id": "58c65788-e377-4e04-9f1a-5defa7bcdc75",
                "row": 4,
                "col": 2,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_kelamin",
                "xmin": 284,
                "ymin": 241,
                "xmax": 326,
                "ymax": 252,
                "score": 0.328807,
                "text": "Perempuan",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "b8449ba4-8f57-4182-b974-5f51f027dbc9",
                "lookup_edited": false
            },
            {
                "id": "44ac8091-51cc-40db-9c0e-34cbf4940b92",
                "row": 4,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "NIK",
                "xmin": 213,
                "ymin": 256,
                "xmax": 280,
                "ymax": 268,
                "score": 0.5004466,
                "text": "300912180001",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "7dfc5ee4-4234-4f8c-a59f-232a89a50019",
                "lookup_edited": false
            },
            {
                "id": "bcd93679-eb7d-49eb-9a93-88697be488a3",
                "row": 4,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "tempat_lahir",
                "xmin": 606,
                "ymin": 235,
                "xmax": 682,
                "ymax": 249,
                "score": 0.53812176,
                "text": "TIDAKNILM SEKOLAH",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "94b31b78-ae3c-4a5f-9e1d-c0dda7c130dd",
                "lookup_edited": false
            },
            {
                "id": "26e67d1d-a9d6-4aa6-9274-1fd618076c9a",
                "row": 4,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "tanggal_lahir",
                "xmin": 488,
                "ymin": 246,
                "xmax": 511,
                "ymax": 256,
                "score": 0.9061622,
                "text": "2-2016",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "8b3da9b8-668a-4959-9b51-5e8ce3b05b95",
                "lookup_edited": false
            },
            {
                "id": "35899299-e1bf-421e-9875-0c605ffd7776",
                "row": 4,
                "col": 7,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_pekerjaan",
                "xmin": 762,
                "ymin": 226,
                "xmax": 854,
                "ymax": 240,
                "score": 0.7127026,
                "text": "BELUM/TIDAK BEKERJA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "4f999028-320c-4f97-8074-52f021ed256c",
                "lookup_edited": false
            },
            {
                "id": "44f351a0-7d7e-4af5-9e39-3edcef4d5e88",
                "row": 4,
                "col": 8,
                "row_span": 1,
                "col_span": 1,
                "label": "golongan darah",
                "xmin": 927,
                "ymin": 222,
                "xmax": 974,
                "ymax": 232,
                "score": 0.7910454,
                "text": "TIDAK TAHU",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "3d69e954-3d41-4b01-a08b-f557eea10c00",
                "lookup_edited": false
            },
            {
                "id": "a2608164-0c27-45e4-a8f7-8b38410c7d30",
                "row": 5,
                "col": 1,
                "row_span": 1,
                "col_span": 1,
                "label": "nama_lengkap",
                "xmin": 58,
                "ymin": 263,
                "xmax": 157,
                "ymax": 277,
                "score": 0.9731105,
                "text": "MINHALA SALIRA ANNOYA",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "10280c92-ae97-4162-93b3-cf4cd39ea92a",
                "lookup_edited": false
            },
            {
                "id": "3a7f899e-7cb6-43c4-91bf-b7cbb5f59e7f",
                "row": 5,
                "col": 2,
                "row_span": 1,
                "col_span": 1,
                "label": "jenis_kelamin",
                "xmin": 283,
                "ymin": 254,
                "xmax": 328,
                "ymax": 265,
                "score": 0.66729337,
                "text": "Perempuan",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "b8449ba4-8f57-4182-b974-5f51f027dbc9",
                "lookup_edited": false
            },
            {
                "id": "7625ff4c-930d-4788-8267-07c55851c44b",
                "row": 5,
                "col": 3,
                "row_span": 1,
                "col_span": 1,
                "label": "NIK",
                "xmin": 213,
                "ymin": 256,
                "xmax": 280,
                "ymax": 268,
                "score": 0.8367868,
                "text": "300912180001",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "7dfc5ee4-4234-4f8c-a59f-232a89a50019",
                "lookup_edited": false
            },
            {
                "id": "c03a4575-4b7d-482b-ab00-a9dbb8fda1fa",
                "row": 5,
                "col": 5,
                "row_span": 1,
                "col_span": 1,
                "label": "tempat_lahir",
                "xmin": 606,
                "ymin": 235,
                "xmax": 682,
                "ymax": 249,
                "score": 0.6916505,
                "text": "TIDAKNILM SEKOLAH",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "94b31b78-ae3c-4a5f-9e1d-c0dda7c130dd",
                "lookup_edited": false
            },
            {
                "id": "ebd06a2f-6ec3-4001-a44d-17e7407c3638",
                "row": 5,
                "col": 6,
                "row_span": 1,
                "col_span": 1,
                "label": "tanggal_lahir",
                "xmin": 488,
                "ymin": 246,
                "xmax": 511,
                "ymax": 256,
                "score": 0.5028289,
                "text": "2-2016",
                "row_label": "",
                "verification_status": "correctly_predicted",
                "status": "",
                "failed_validation": "",
                "label_id": "8b3da9b8-668a-4959-9b51-5e8ce3b05b95",
                "lookup_edited": false
            }
        ],
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "4a419c56-fc8a-4463-872b-7f40c9857d1e",
        "label": "alamat",
        "xmin": 234,
        "ymin": 118,
        "xmax": 319,
        "ymax": 136,
        "score": 0.89144176,
        "ocr_text": "KETAON SELATAN",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "708106f9-3b62-4b90-b77c-f22ac1f295b5",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "8e481297-aa4d-4582-9272-275466dc3ae6",
        "label": "rt_rw",
        "xmin": 234,
        "ymin": 134,
        "xmax": 269,
        "ymax": 146,
        "score": 0.9681575,
        "ocr_text": "019/003",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "b3136536-e040-49b9-9316-a2727a433240",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "1684bbcc-221a-4a25-99d2-d8ce9ae569ff",
        "label": "tanggal_dikeluarkan",
        "xmin": 161,
        "ymin": 548,
        "xmax": 209,
        "ymax": 561,
        "score": 0.9568888,
        "ocr_text": "02-03-2022",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "622ed882-dfdb-4570-848c-53b6c40a9df2",
        "lookup_edited": false,
        "lookup_parent_id": ""
    },
    {
        "id": "a7dd3bf8-348e-49c5-86bf-29f78aec98fe",
        "label": "provinsi",
        "xmin": 722,
        "ymin": 105,
        "xmax": 807,
        "ymax": 121,
        "score": 0.9862802,
        "ocr_text": "JAWA TENGAH",
        "type": "field",
        "status": "correctly_predicted",
        "page_no": 0,
        "label_id": "6e9e6eca-10a7-4d6f-915c-ccfdc715b5cb",
        "lookup_edited": false,
        "lookup_parent_id": ""
    }
]

// Initialize output object
const output = {
    no_kk: '',
    table: [],
};

// Extract no_kk
input.forEach((item) => {
    if (item.label === 'no_kk') {
        output.no_kk = item.ocr_text.replace('No ', '');
    }
});

const table = {
    row: '',
    value: '',
};

// Extract NIK, nama_lengkap, and status_perkawinan
const nikArray = [];
const nameArray = [];
const genderArray = [];
const dobArray = [];
const pobArray = [];
const educationArray = [];
const jobArray = [];
const statusArray = [];
const relationArray = [];
const citiArray = [];
const religionArray = [];
const fatherArray = [];
const motherArray = [];


input.forEach((item) => {
    if (item.label === 'table' && item.cells) {
        item.cells.forEach((cell) => {
            if (cell.label === 'NIK') {
                nikArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'nama_lengkap') {
                nameArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'tempat_lahir') {
                pobArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'tanggal_lahir') {
                dobArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'jenis_pekerjaan') {
                jobArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'status_perkawinan') {
                statusArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'status_hubungan') {
                relationArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'kewarganegaraan') {
                citiArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'agama') {
                religionArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'ortu_ayah') {
                fatherArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
            if (cell.label === 'ortu_ibu') {
                motherArray.push({ row: cell.row, col: cell.col, value: cell.text });
            }
        });
    }
});

// const nikArray = [];
// const nameArray = [];
// const genderArray = [];
// const dobArray = [];
// const pobArray = [];
// const educationArray = [];
// const jobArray = [];
// const statusArray = [];
// const relationArray = [];
// const citiArray = [];
// const religionArray = [];
// const fatherArray = [];
// const motherArray = [];

console.log({
    nikArray, nameArray, genderArray,
    dobArray, pobArray, educationArray,
    jobArray, statusArray, relationArray,
    citiArray, religionArray, fatherArray, motherArray
});

const maxLength = Math.max(nikArray.length, pobs.length);

for (let i; maxLength; i++) {
    output.table.push({
        nik: nikArray,
    });
}

// Combine NIK, nama_lengkap, and status_perkawinan into table array
// nikArray.forEach((nik, index) => {
//   output.table.push({
//     NIK: nik,
//     nama_lengkap: namaArray[index] || '', // Handle potential mismatch in array lengths
//     status_perkawinan: statusArray[index] || '', // Handle potential mismatch in array lengths
//     status_hubungan: relationArray[index] || '', // Handle potential mismatch in array lengths
//     agama: agama[index] || '', // Handle potential mismatch in array lengths
//     dob: dobs[index] || '',
//     tempat_lahir: pobs[index] || '',
//   });
// });

// Convert output object to array
const result = [output];

// Log the result
console.log(result);